server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: zuul-service
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
